# Generated by Django 5.2 on 2025-04-10 06:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Dona')], max_length=10, verbose_name='Oʻlchov birligi')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi (birlik uchun)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Masalliq',
                'verbose_name_plural': 'Masalliqlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Kerakli miqdor')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('prepared', 'Tayyorlangan'), ('purchased', 'Sotib olingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='main.ingredient', verbose_name='Masalliq')),
            ],
            options={
                'verbose_name': 'Masalliq hisobi',
                'verbose_name_plural': 'Masalliq hisoblari',
                'ordering': ['date', 'ingredient'],
                'unique_together': {('date', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram foydalanuvchi ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Mijoz ismi')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holati')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Umumiy summa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izohlar")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Umumiy narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Miqdori')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_products', to='main.ingredient', verbose_name='Masalliq')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='main.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot masalliqi',
                'verbose_name_plural': 'Mahsulot masalliqlari',
                'unique_together': {('product', 'ingredient')},
            },
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='main.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='main.ProductIngredient', to='main.ingredient', verbose_name='Masalliqlar'),
        ),
    ]
